DELETE FROM PLAYERS;
INSERT INTO PLAYERS (PLAYERID, NAMEFIRST, NAMELAST) VALUES ('1', 'Alice', 'Zephyr');
INSERT INTO PLAYERS (PLAYERID, NAMEFIRST, NAMELAST) VALUES ('2', 'Bob', 'Yellow');
INSERT INTO PLAYERS (PLAYERID, NAMEFIRST, NAMELAST) VALUES ('3', 'Carol', 'Adams');
